# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

spca_Rcpp <- function(X1, sparsity, w1, lambda = 10000L, bess_tol = 1e-3, bess_maxiter = 100L) {
    .Call('_bspcaRcpp_spca_Rcpp', PACKAGE = 'bspcaRcpp', X1, sparsity, w1, lambda, bess_tol, bess_maxiter)
}

